version: "3"

services:

  elasticsearch:
    image: elasticsearch:8.1.2
    volumes:
      - es/es:/usr/share/elasticsearch/data:z
      - es/logs:/usr/share/elasticsearch/logs:z
    expose:
      - 9200
    env_file: .env
    restart: always

  postgres:
    image: postgres:12.2
    volumes:
      - pp:/var/lib/postgresql/data:z
    expose:
      - ${POSTGRES_PORT}
    env_file: .env
    restart: always

  web:
    build: rest
    restart: always
    command: ${SERVE_COMMAND}
    volumes:
      - ./rest/app:/vol/app:z
      - ppstatic:/vol/static_files:z
      - ${REAL_IMAGE_DIR}:/vol/img:z
    expose:
      - 8000
    links:
      - "postgres:postgres"
      - "elasticsearch:elasticsearch"
    env_file: .env
    depends_on:
      - postgres
      - elasticsearch

  nginx:
    image: nginx:1.17.10
    restart: always
    volumes:
      - ppstatic:/vol/static_files:z
      - ${REAL_IMAGE_DIR}:/vol/img:z
      - ./nginx:/etc/nginx/conf.d:z
    ports:
      - "443:443"
      - "80:80"
    env_file: .env
    links:
      - "web:web"
      - "iiif:iiif"
    depends_on:
      - web
    command: sh -c "envsubst '$$ALLOWED_HOSTS $$CERT_PATH $$KEY_PATH $$PP_NGINX_LISTEN $$PP_NGINX_SERVER_NAME $$HTTPS_REDIRECT' < /etc/nginx/conf.d/pp.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  iiif:
    image: mdlincoln/go-iiif-vips:latest
    restart: always
    volumes:
      - ./iiif:/etc/iiif-server:z
      - ${REAL_IMAGE_DIR}:/usr/local/images:z
    expose:
      - 80
    command: "/bin/iiif-server -host 0.0.0.0 -port 80 -config-source file:///etc/iiif-server -config-name config.json"

volumes:
  pp:
  es:
  ppstatic:
